version: "3.7"

services:
  apigateway:
    image: traefik:v2.0.1
    ports:
      - "5090:80" # Port of the API Gateway, which will be the port behind which the system will be published
      - "5098:8080" # Dashboard of Traefik for troubleshooting
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events (see .env file for Windows workaround to make this work)
    networks:
      - todoapp-network

  todos:
    image: "${REGISTRY_URL:-todoapp}/todos:${IMAGE_TAG:-latest}"
    build:
      context: .. # Parent directory, since this file is under the 'Docker' subfolder; every path in every Dockerfile is relative to this
      dockerfile: Todos/Todos.Api/Dockerfile # The Dockerfile to build; path is relative to the context, which is the solution root
    networks: # All microservices are connected by this private Docker network, which also provides DNS
      - todoapp-network
    labels:
      - "traefik.enable=true" # Enable publishing this service by Traefik
      - "traefik.http.routers.todos.rule=PathPrefix(`/api/todos`)" # Routing rule
      - "traefik.http.middlewares.todos-auth.forwardauth.address=http://users/api/auth" # Forward authentication middleware definition
      - "traefik.http.routers.todos.middlewares=todos-auth@docker" # Use the auth middleware in the /api/users route

  web:
    image: "${REGISTRY_URL:-todoapp}/web:${IMAGE_TAG:-latest}"
    build:
      context: ..
      dockerfile: Web/Docker/Dockerfile
    networks:
      - todoapp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)" # Routing rule

  users:
    image: "${REGISTRY_URL:-todoapp}/users:${IMAGE_TAG:-latest}"
    build:
      context: ..
      dockerfile: Users/Docker/Dockerfile
    networks:
      - todoapp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/auth`)" # Two routing rules are defined: this one, for the authentication, can be called by anyone
      - "traefik.http.routers.users.rule=PathPrefix(`/api/users`)" # This other rule works on a different url scheme, and requires authentication
      - "traefik.http.middlewares.users-auth.forwardauth.address=http://users/api/auth" # Forward authentication middleware definition
      - "traefik.http.routers.users.middlewares=users-auth@docker" # Use the auth middleware in the /api/users route

  mongodb:
    image: mongo:4.0.12
    networks:
      - todoapp-network
    volumes:
      - todoapp-mongo-data:/data/db

  redis:
    image: redis:5.0.5-alpine
    networks:
      - todoapp-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    environment:
      - cluster.name=elasticsearch # Settings to start Elasticsearch in a single-node development environment
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - todoapp-elastic-data:/usr/share/elasticsearch/data
    networks:
      - todoapp-network

  logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: logs
    environment:
      - cluster.name=logs # Settings to start Elasticsearch in a single-node development environment
      - node.name=logs
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9202:9200"
    volumes:
      - logs-elastic-data:/usr/share/elasticsearch/data
    networks:
      - todoapp-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana
    environment: 
      - ELASTICSEARCH_HOSTS=http://logs:9200
    ports:
      - "5602:5601"
    depends_on:
      - logs
    networks:
      - todoapp-network

volumes: # The volumes will store the database data; kept even after the containers are deleted
  todoapp-mongo-data:
    driver: local
  todoapp-elastic-data:
    driver: local
  logs-elastic-data:
    driver: local


networks:
  todoapp-network:
    driver: bridge
